[package]
name = "day02"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
nom = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
