[package]
name = "day05"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
nom = { workspace = true }
